# Version file generated by setuptools-scm
"""Version information for symbolic-mcp"""

__version__ = "0.1.0"

# Version metadata
version_info = {
    "version": "0.1.0",
    "git_version": "0.1.0",
    "is_git_repo": True,
}

# Compatibility information
try:
    from .version_manager import VersionManager

    vm = VersionManager()
    fastmcp_compatibility = vm.get_fastmcp_compatibility()
except ImportError:
    fastmcp_compatibility = {
        "version": "unknown",
        "compatibility": "unknown",
        "message": "FastMCP not available",
        "required": ">=2.0.0",
    }

__fastmcp_compatibility__ = fastmcp_compatibility
